---
efiSystemPartition: "/boot/efi"
enableLuksAutomatedPartitioning: true
userSwapChoices:
  - none
  - file
initialSwapChoice: file
drawNestedPartitions: true
defaultFileSystemType: "ext4"
defaultPartitionTableType: gpt
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
